import Head from 'next/head'
import Category from '../src/components/Category'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-kayan h-screen w-screen flex justify-center items-center'>
        <div className='md:w-[600px] p-3'>
        <Category background='bg-panyaung' label='PLAYER VS CPU' isCpu={true}/>
        <Category background='bg-awar' label='PLAYER VS PLAYER'/>
        <Category background='bg-white' label='GAME RULES' isRule={true}/>
   
        </div>
      </main>
    </>
  )
}
